### PR TITLE
My Rails Solution

### PR DESCRIPTION
**Pull request by jamesstonehill**
Just in case you're wondering, the reason why I included a local version of the Geokit gem is because I ran into an issue with the gem and I was trying to fix it:
https://github.com/geokit/geokit-rails/issues/113

### CODE REVIEW

**Comment by mattschofield** [comment]
@jamesstonehill thanks so much for submitting this PR! I'm aiming to have a proper review over the next day or so. Let me know if you were planning on adding any more to the repo, otherwise I'll just review as-is 👍

**Comment by jamesstonehill** [comment]
Hi Matt,

Thanks, I look forward to hearing your thoughts on the solution! I won't be
adding anything code wise so feel free to look at it whenever you have the
time.

Regards,
James

**Comment by jamesstonehill** [comment]
Hi Matt,

Really sorry to hassle you, but I'm just wondering if you've had a chance
to review my tech test?

Regards,
James

**Comment by mattschofield** [comment]
Hi @jamesstonehill - should have a review done by EOD.

**Comment by mattschofield** [comment]
James, thanks for submitting this PR - apologies it's taken me a while to review. Some feedback for you (I'll be feeding back to Makers separately):

1) Nice simple Rails app, minimal fuss - enough for a challenge of this scale 👍 
2) RE: testing, I would've liked to see some as it aids the thought process, but I think (given you're using Rails and not just vanilla Ruby) this would've been more applicable at later stages of the challenge if you'd got round to them.
3) Stylistically, the code is a little sloppy - I'd recommend adopting a [style guide](https://github.com/airbnb/ruby). If you want to know *why* I'd recommend it, check the first comment on [this](https://github.com/airbnb/javascript/issues/102) thread.
4) For future reference, I'd recommend you look into [squashing your commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html). This helps you avoid tiny, meaningless commits that bloat your PRs 😉 

As a point of reference, I've added you as a collaborator on my ["solution"](https://github.com/mattschofield/kudomon-solution) to the challenge. You're welcome to ask any questions on it if it's of interest!

All the best,
M

**Comment by jamesstonehill** [comment]
Hi Matt,

Thanks for the feedback. You've given a lot of really constructive advice
here so thanks for that! Sorry again for pushing you for a response on the
tech test earlier this week. Normally I wouldn't care about the feedback
timeframe, but I'm close to signing a contract with a company and I'm just
keen to explore all my options now before committing to join somewhere.

Have a good weekend and best of luck in finding a suitable candidate.

Regards,
James

**Pull request closed without merging**
